# Generated by Django 2.1.7 on 2019-02-20 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagador_nome', models.CharField(max_length=128)),
                ('pagador_banco', models.CharField(max_length=3)),
                ('pagador_agencia', models.CharField(max_length=4)),
                ('pagador_conta', models.CharField(max_length=6)),
                ('beneficiario_nome', models.CharField(max_length=128)),
                ('beneficiario_banco', models.CharField(max_length=3)),
                ('beneficiario_agencia', models.CharField(max_length=4)),
                ('beneficiario_conta', models.CharField(max_length=6)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('ERRO', 'ERRO')], max_length=12)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
        ),
    ]
