# Generated by Django 2.1.7 on 2019-02-20 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
